[package]
name = "plaintext-social"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.11.0"
chrono = "0.4.41"
lazy_static = "1.5.0"
serde = { version = "1.0.219", features = ["derive"] }
tera = "1"

